import { withRetry } from "@/lib/db";
import { blogPosts } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";
import { sanitizeHtml } from "@/lib/sanitize";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = await withRetry((db) => db.query.blogPosts.findFirst({
    where: eq(blogPosts.slug, slug),
  }));

  if (!post || !post.isPublished) return { title: "Post Not Found" };

  return {
    title: `${post.title} | Festo Wampamba`,
    description: post.excerpt || "Read this insightful article.",
  };
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;

  // Avoid relational `with` query — Neon HTTP driver can fail on it.
  // Fetch post and author as two separate simple queries instead.
  const post = await withRetry((db) =>
    db.query.blogPosts.findFirst({ where: eq(blogPosts.slug, slug) })
  );

  if (!post || !post.isPublished) notFound();

  const dateStr = new Date(post.publishedAt || post.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Basic styling for the rich text HTML content generated by Tiptap
  // This uses Tailwind's arbitrary variants to style descendant elements generically.
  const contentStyles = `
    [&>h1]:text-white-2 [&>h1]:text-3xl [&>h1]:font-bold [&>h1]:mb-6
    [&>h2]:text-white-2 [&>h2]:text-2xl [&>h2]:font-bold [&>h2]:mt-8 [&>h2]:mb-4
    [&>h3]:text-white-2 [&>h3]:text-xl [&>h3]:font-semibold [&>h3]:mt-6 [&>h3]:mb-3
    [&>p]:text-light-gray [&>p]:mb-5 [&>p]:leading-relaxed
    [&>ul]:list-disc [&>ul]:pl-6 [&>ul]:mb-6 [&>ul]:text-light-gray [&>ul>li]:mb-2
    [&>ol]:list-decimal [&>ol]:pl-6 [&>ol]:mb-6 [&>ol]:text-light-gray [&>ol>li]:mb-2
    [&>blockquote]:border-l-4 [&>blockquote]:border-orange-yellow-crayola [&>blockquote]:pl-4 [&>blockquote]:italic [&>blockquote]:text-light-gray-70 [&>blockquote]:mb-6
    [&>hr]:border-jet [&>hr]:my-8
    [&>pre]:bg-eerie-black-1 [&>pre]:text-light-gray [&>pre]:p-4 [&>pre]:rounded-xl [&>pre]:overflow-x-auto [&>pre]:mb-6 [&>pre]:font-mono [&>pre]:text-sm
    [&>p>code]:bg-eerie-black-1 [&>p>code]:text-orange-yellow-crayola [&>p>code]:px-1.5 [&>p>code]:py-0.5 [&>p>code]:rounded-md [&>p>code]:font-mono [&>p>code]:text-sm
    [&>p>strong]:text-white-2 [&>p>strong]:font-semibold
    [&>p>em]:italic
  `;

  return (
    <article className="animate-in fade-in duration-500 max-w-3xl mx-auto pb-10">
      <div className="mb-8">
        <Link
          href="/blog"
          className="inline-flex items-center gap-2 text-orange-yellow-crayola hover:text-orange-400 font-medium text-sm transition-colors mb-6"
        >
          <ChevronLeft className="w-4 h-4" /> Back to all articles
        </Link>
        <h1 className="text-white-2 text-[32px] sm:text-[40px] font-bold leading-tight mb-4">
          {post.title}
        </h1>
        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 text-light-gray-70 text-sm font-medium">
          <span>{dateStr}</span>
          <span className="hidden sm:inline text-jet">•</span>
          <span className="bg-orange-yellow-crayola/10 text-orange-yellow-crayola px-2.5 py-1 rounded-md text-xs tracking-wide">
            {post.category || "Uncategorized"}
          </span>
        </div>
      </div>

      {post.coverImage && (
        <div className="w-full mb-12 rounded-2xl overflow-hidden border border-jet bg-eerie-black-1 flex items-center justify-center">
          <Image
            src={post.coverImage}
            alt={post.title}
            width={900}
            height={600}
            className="w-full h-auto max-h-[600px] object-contain"
            priority
          />
        </div>
      )}

      {/* Render sanitized HTML from Tiptap database */}
      {post.content ? (
        <div
          className={contentStyles}
          dangerouslySetInnerHTML={{ __html: sanitizeHtml(post.content) }}
        />
      ) : (
        <p className="text-light-gray italic">No content available.</p>
      )}
    </article>
  );
}
